# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: On Push - All Branches

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE_PATH: "\"src/Roadbed .NET Solution.slnx\""
      PROJECT_FILE_PATH: "\"src/Roadbed.Test.Unit/Roadbed.Test.Unit.csproj\""

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    
    - name: Setup .NET 10
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: 10.0.x
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --no-restore
      
    - name: Test
      run: dotnet test ${{ env.PROJECT_FILE_PATH }} --no-build --verbosity normal
